apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./secret.sops.yaml
  - ./cronjob.yaml
configMapGenerator:
  - name: plex-trakt-sync-config
    files:
      - config/config.yml
      - config/.pytrakt.json
      - config/servers.yml
      - config/.env
generatorOptions:
  disableNameSuffixHash: true
