cache:
  path: /app/config/trakt_cache

logging:
  append: true
  debug: false
  filename: plextraktsync.log

sync:
  plex_to_trakt:
    collection: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: false
    watchlist: false

watch:
  username_filter: true
  scrobble_threshold: 80
